### ISSUE TITLE
Bug in make_parameters.jl

### ISSUE THREAD

**Issue by CleggTom** [PoisotLab/BioEnergeticFoodWebs.jl#15]
## Expected behavior
- Creation of Parameters Dictionary with supplied body mass.

 

## Actual behavior
- Metabolic rates `x` are set to `inf` in the Dictionary if body mass is supplied. 
- Results in an error when the simulation is run.

## Steps to reproduce

1. Set up simulation as per the getting started example in the documents
2. Set body mass in the model_parameters function

## System information

- `julia 0.5.1`
- `BioEnergeticFoodWebs   0.3.0`
- OSX 10.10.5

**Comment by tpoisot** [comment]
PR opened to publish the next release: https://github.com/JuliaLang/METADATA.jl/pull/8423

Thanks @TomClegg94
