### ISSUE TITLE
More precise usage of DifferentialEquations.jl

### ISSUE THREAD

**Issue by ChrisRackauckas** [PoisotLab/BioEnergeticFoodWebs.jl#28]
I see you are using DifferentialEquations.jl directly. For your case, you may want to use some of the specific components instead. This will reduce the size of the dependency and the associated installation time. This setup is documented here:

http://docs.juliadiffeq.org/latest/features/low_dep.html

Note that if you do this change, the automatic algorithm selection is disabled. You would have to provide the algorithm choices to the `solve` command. I would recommend for your purposes `Tsit5()` for non-stiff equations and `CVODE_BDF()` for stiff equations, and thus depend directly on DiffEqBase, OrdinaryDiffEq, and Sundials.

Let me know if you need any help.

**Comment by tpoisot** [comment]
Thanks @ChrisRackauckas  -- indeed interested in this, but I'll wait until 0.6 is released and fix this with all other deprecations.

**Comment by ChrisRackauckas** [comment]
Alright. BTW, the DiffEq depwarns are all fixed on v0.6, but you will still get depwarns from us until IterativeSolvers.jl and NLsolve.jl merge my depwarn fixes.

**Comment by ChrisRackauckas** [comment]
Could you describe your DiffEqs a little bit? Size and tolerance? I'll set this up to use the lower dependency version but keep some of the default handling.
