### ISSUE TITLE
Rewiring

### ISSUE THREAD

**Issue by tpoisot** [PoisotLab/BioEnergeticFoodWebs.jl#29]
Seems like @TomClegg94 has implemented some rewiring -- do you want to submit this as a pull request here? @evadelmas was thinking about working on this too in the future.

**Comment by CleggTom** [comment]
Sorry about the first request, Github is still confusing for me. I've added what i've got so far with some comments. Here is some example code to get both rewiring types running: 
```
using BioEnergeticFoodWebs
#example using the ADBM
A = nichemodel(10, 0.3)
p = model_parameters(A,Z = 10.0)
p_r = rewire_parameters(:ADBM,A=A)
b = rand(size(A, 1)) .* 10
A = BioEnergeticFoodWebs.ADBM(10,p,b,p_r)
p = model_parameters(A, Z = 10.0)

s = simulate(p, p_r, b, start=0, stop=500, use = :nonstiff)

#example using Gilljam's method
A = nichemodel(10, 0.3)
p = model_parameters(A,Z = 10.0)
p_r = rewire_parameters(:Gilljam,preferenceMethod = :specialist, A=A)
p = BioEnergeticFoodWebs.getW_preference(p,p_r,10)
biomass = rand(size(A, 1))

s = simulate(p, p_r, biomass, start=0, stop=100, use = :nonstiff)
```

**Comment by evadelmas** [comment]
I am almost done implementing Staniczenko's rewiring method. I was thinking that it would be a bit easier if we merge the rewire_parameters() and the model_parameters() functions (I have done it locally and it works fine). That would result in something like:
```
A = nichemodel(10, 0.2)
p = model_parameters(A, rewire_method = :ADBM, Hmethod = :ratio, Nmethod = :original)
#etc.
``` 
What do you think ?

**Comment by tpoisot** [comment]
This is going to result in a  `model_parameters` function with a *lot* of keywords, right? This is not necessarily an issue, but this needs to be considered. Maybe the documentation for this function needs to be expanded a bit.

**Comment by evadelmas** [comment]
We now have 18 keywords, we would have 33 if we merge the two. That's a lot but I think it still makes it less confusing, with everything in the same object. Especially as parameters such as efficiency or hill coef. seem to appear in both functions in different forms (if I understood it correctly). It would indeed require to add a bit to the documentation.

**Comment by evadelmas** [comment]
@TomClegg94  We have merged your pull request into the branch *rewiring* and opened a new pull request from *rewiring* to *next*. This new pull request will be used for all rewiring related discussions.

**Comment by tpoisot** [comment]
The pull request in question is #32
