### ISSUE TITLE
Doc page with extinction examples

### ISSUE THREAD

**Issue by tpoisot** [PoisotLab/BioEnergeticFoodWebs.jl#41]
@evadelmas / @TomClegg94 

I'm ready to merge `next` into `master` and go forth with a new release (when #40 is done) -- before we do this, the doc needs a page about extinctions. 

I added an empty file at `docs/src/man/extinctions.md` -- please add something short and sweet.

Great work all around.

**Comment by CleggTom** [comment]
I've added the beginning of the docs with #42. 

We still need to add the various rewiring parameters as a docstring somewhere. It's not exactly clear where though as there is no `rewiring_parameters` and the `make_parameters` docs are fairly long already.
