### ISSUE TITLE
ADBM function does not return the correct matrix

### ISSUE THREAD

**Issue by evadelmas** [PoisotLab/BioEnergeticFoodWebs.jl#46]
Hi @TomClegg94, 

I was going through the tests today and it seems that the `ADBM` function (or more probably the `get_feeding_links` function) does not return the expected rewired matrix. This is true regardless of the method used (ratio, power or biomass). Would you have some time to check if there is indeed a bug in the code or if it's a problem with the tests? 
Thanks

**Comment by evadelmas** [comment]
@TomClegg94 
It actually seems that there is a problem with the tests, not with the functions. If I am correct, 

```julia
 S = 5
 A = [0 0 0 0 0; 0 1 0 0 0; 0 0 0 0 0; 0 1 1 0 0; 0 1 1 1 1]
 biomass = [1.0,1.0,1.0,0.0,1.0]
 p = model_parameters(A, rewire_method = :ADBM, Hmethod = :ratio, Z = 10.0)
 ADBMTest = BioEnergeticFoodWebs.ADBM(S,p,biomass)
```

should return 

```julia
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
1 1 1 0 0
```
and not 
```julia
0 0 0 0 0
0 0 0 0 0
0 0 0 0 0
1 1 1 0 0
1 1 1 1 0
```
as species 4 is extinct (`biomass[4] == 0.0`). From what I understand, there was a bug until you changed the `get_feeding_links` function by giving a negative profit to extinct species (`profit[biomass .== 0.0] = -1.0`).

**Comment by CleggTom** [comment]
Hi @evadelmas,

I haven't had a chance to look into it but I think you're right. The test was written before the bug was fixed in that commit so it probably needs updating itself. 

I'll have a closer look this weekend.
