### ISSUE TITLE
Template for temperature functions

### ISSUE THREAD

**Issue by tpoisot** [PoisotLab/BioEnergeticFoodWebs.jl#57]
Some ideas about how to make a general interface for temperature functions.

All function have the form

```julia
function fname(params)
    return (p,t) -> something
end
```

So for example, with a Gaussian:

```julia
function gaussian(params)
    return (x,t) -> x * exp(-((params.optimal-t)^2/(2*params.dispersal^2))
end
```

This means that we can have something like

```julia
params = (optimal = 20.0, dispersal = 0.4)
handling_time = gaussian(params)
```

and for any default value of handling time at any temperature, we can call

```julia
handling_time(default_value, temperature)
```

The cool thing is that if all functions (`gaussian`, `arrhenius`, etc) are defined in the same way, we can do something like

```julia
function simulation(...., handling::(gaussian, default, params), attack::(arrhenius, default, params), ...)
```

which defines the behavior of all parameters as functions and parameters. We can also have a function for no response to temperature, defined as 

```julia
function no_effect(params)
    return (x, t) -> x
end
```

(this returns the default value).

Let me know if that makes sense, but I think this is the more general approach -- it basically puts the parameterization of temperature functions *outside* of the model, so we can possibly get this done with minimal modifications to the internal code.

**Comment by tpoisot** [comment]
*PS* you might want to actually try this to get a sense of what that does,but functions returning function seems like a useful pattern here.

**Comment by evadelmas** [comment]
That looks great! So far we managed to do something like 
```
using NamedTuples
params = @NT(norm_constant = 0.2e11, activation_energy = 0.65, β = -0.25)
function exponentialBA(params)
       return (bodymass, temperature) -> params.norm_constant.*((bodymass.^params.β).*exp.(-params.activation_energy./(8.617e-5*temperature)))
end
handling_time = exponentialBA(params)
```
which is working: 
``` 
handling_time(1, 295)
``` 
But we don't get how to call the function in `simulate`, because this:
```
handling::(gaussian, default, params)
```
is not working.

**Comment by Azenor** [comment]
We probably figured it out : 
```
handling(tempfunc::Function, par) = tempfunc(par)
handling(exponentialBA, params)(1,295)
```
where 1 is body mass and 295 is temperature.

**Comment by tpoisot** [comment]
Yep, I think something like this makes sense. You can decide to either pass the function directly, or a tuple with (function, parameters), but this should be relatively general.
