### ISSUE TITLE
DomainError for some values of  the hill exponent

### ISSUE THREAD

**Issue by Azenor** [PoisotLab/BioEnergeticFoodWebs.jl#76]
When using some values of h different from 1.0 or 2.0, we get a DomainError when executing the function `simulate()`. It seems to occur with the keywords `:species`, `:system`, `:competitive` but not with `:nutrients`. 

Reproducible example : 

```
A = [0 0 0 0 0; 1 0 1 0 0; 1 0 0 0 0; 0 1 0 0 0; 0 0 0 0 0] ;
p = model_parameters(A, productivity = :system, h = 1.2);
s = simulate(p, rand(p[:S]), stop=1000)
```
Error obtained : 

```
ERROR: DomainError with -6.825133204115963e-9:
Exponentiation yielding a complex result requires a complex argument.
Replace x^y with (x+0im)^y, Complex(x)^y, or similar.
```

It seems to come from the matrix structure. When removing one link such that `A = [0 0 0 0 0; 1 0 1 0 0; 0 0 0 0 0; 0 1 0 0 0; 0 0 0 0 0]`, it works.

## System information

- `julia --version`
- `Pkg.status("BioEnergeticFoodWebs")`
- OS and version

**Comment by evadelmas** [comment]
Hi @Azenor 
Biomass values can temporary drop below 0 by up to 1e-6 which causes this `DomainError` when the hill exponent is 1<h<2. Should be fixed now (on the `next` branch at least, I'm planning on merging to master in the next few days).
