### ISSUE TITLE
Warning when running simulate(); canceled iteration

### ISSUE THREAD

**Issue by kwootton** [PoisotLab/BioEnergeticFoodWebs.jl#77]
- When running simulate() I sometimes (but not always) get warnings about cancelled iterations. Simulate still runs and I still get the output. 

I get zombies (species that go extinct or nearly extinct and then come back). I'm not sure if this is due to the warning, or if the package doesn't have a control to avoid zombies (but it looks like you do), or if the threshold for extinctions is just lower than I think it is.

## Actual behavior

┌ Warning: Could not restrict values to domain. Iteration was canceled since
│   time step dt =  = "time step dt = "
│   integrator.dt = 2.220446049250313e-16
│    could not be reduced. = " could not be reduced."
└ @ DiffEqCallbacks C:\Users\kewo0002\.julia\packages\DiffEqCallbacks\rV4BA\src\domain.jl:98

## Steps to reproduce

1. foodweb = build_foodweb(50, 0.1);
2. params = model_parameters(foodweb);
3. bm = rand(size(foodweb,1));
4. sim = simulate(params, bm, start = 0, stop = 100);

## System information

- `julia --version` Version 1.1.0
- `Pkg.status("BioEnergeticFoodWebs")`   BioEnergeticFoodWebs v1.0.0
- OS and version  Windows 10 (but we're also getting this error with Linux)

**Comment by evadelmas** [comment]
Hi @kwootton
I have modified the `simulate`function, it should fix these issues. Among other things, I have added two arguments that should give you a better control on extinctions : `cb_interp_points` (default to 100) lets you control the number of interpolated points to check the condition (extinction), if some extinction events are not detected you can try increasing this number (it will be slower though). `extinction_threshold` (default to `100*eps()`) lets you set the biomass threshold below which species will be considered as extinct (and their biomass set to `0.0`). I was not able to test it on your example as I do not have the `build_foodweb` function. Could you please try and see if it works (on the `zombie_species` branch)?  Here is a short example:
```
]add BioEnergeticFoodWebs#zombie_species
using BioEnergeticFoodWebs
A = [0  0  0  0  0  0  0  0  0  0;
       0  0  0  0  0  0  0  0  0  0;
       0  0  1  0  0  0  0  0  0  0;
       0  0  1  1  0  0  0  0  0  0;
       1  1  0  0  0  0  0  0  0  0;
       0  1  0  0  0  0  0  0  0  0;
       0  1  1  1  0  0  0  0  0  0;
       0  0  0  0  0  1  1  1  1  0;
       0  0  0  0  1  0  0  0  0  0;
       1  1  1  1  1  1  1  1  1  1]
biomass = [0.5606323505656658; 
                  0.617768218959883;   
                  0.348147175487846;   
                  0.14145571932309609; 
                  0.024836804720612893;
                  0.25532974997751534; 
                  0.9509612502009055;  
                  0.9258011745343453;  
                  0.5666604811658187;  
                  0.6214988281021347]
parameters = model_parameters(A)
simulate(parameters, biomass, stop = 1000, use = :stiff, cb_interp_points = 100, extinction_threshold = 100*eps())
```

**Comment by ChrisRackauckas** [comment]
100eps() may be smaller than you can reliably ever get to, which would be the cause of this problem. A good idea would probably be to set this at around the absolute tolerance in the integration. `100eps()` would correspond to solving with `abstol=1e-14` which is usually complete overkill, not to mention computationally expensive. The only way I can see that working is if you're using something like `PositiveCallback()` and that is interpolating to make it as close as possible to the zero?

**Comment by kwootton** [comment]
Hi @evadelmas and @ChrisRackauckas 

Sorry, the build_foodweb function is essentially just the nichemodel function from the package, I copied the wrong line.

Using the example you have here the zombie_species branch works. The only hitch I've found so far is if I set extinction_threshold too high then the simulation gets stuck (0.00001 with S=50 and C=0.1 seems to be where it gets stuck, while 0.000001 is OK. Using the smaller food web you have above I don't get this problem).

The warnings from the simulate function seem to be gone now, thanks!!

Kate

**Comment by evadelmas** [comment]
@ChrisRackauckas thanks for your advice. We do have biomass going as small as 1e-19 in almost all of our simulations, setting 1e-14 as the extinction threshold seems to work fine with the new callback condition, but I see your point with it being computationally expensive, I will change the default to something like 1e-6 (which is the default for `abstol` if I remember correctly). 
@kwootton I'll try to reproduce this problem and see what I can do, it might be that some foodwebs have structures that makes solving the problem more difficult (especially with the niche model). When you say it get stuck, is it that it's taking very long or not solving at all? Is their an error message? 
edit: I was not able to reproduce this problem. Can you please share an example using `Random.seed!` or the foodwebs matrix and initial biomass?

**Comment by kwootton** [comment]
I actually can't reproduce the problem now either! It was just taking significantly longer than when the threshold was lower, to the point that I gave up on waiting for it. Now it looks to be absolutely fine though, so perhaps it was just a particular network structure than was more difficult to solve and I wasn't patient enough!
